name: CI (test)

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup python
        uses: action/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r ./01-ci-lab/requirements.txt

      - name: Run test
        run: pytest ./01-ci-lab
